/*!
@file Project.h
@brief コンテンツ用のヘッダをまとめる
*/

#pragma once
//メイン
#include "Scene.h"
#include "MainCamera.h"
#include "TitleCamera.h"
#include "PlayerModel.h"
#include "Player.h"
#include "CSVLoad.h"
#include "Debug.h"
#include "AdvCollision.h"
#include "MyMath.h"
#include "Utility.h"
//ステージ関係
#include "TitleStage.h"
#include "SelectStage.h"
#include "GameStage.h"
#include "ResultStage.h"
#include "LoadStage.h"
//メニュー
#include "TitleModel.h"
#include "StringSprite2.h"
#include "BaseMenu.h"
#include "TitleMenu.h"
#include "PauseMenu.h"
#include "ResultMenu.h"
#include "SelectStageMenu.h"
#include "Cursor.h"
//UI関係
#include "Numbers.h"
#include "FrameSprite.h"
#include "illusionFrame.h"
#include "BGSprite.h"
#include "ImageSprite.h"
#include "PictureFrame.h"
#include "SceneTransition.h"
#include "Fade.h"
#include "Result.h"
#include "UI_Player.h"
#include "UI_Goalgauge.h"
#include "UI_LR.h"
#include "Pause.h"
//行動やコンポーネント
#include "SinCurve.h"
#include "SquareMove.h"
#include "CircularMove.h"
#include "LinearMove.h"
#include "RouteMove.h"
#include "FadeComponent.h"
//エフェクト
#include "Effect.h"
//トリックアート
#include "TrickArtSystem/TrickArtSystem.h"
#include "illusionModel.h"
//ステージオブジェクト
#include "StageObject.h"
#include "FallingArea.h"
#include "StartPoint.h"
#include "StaticPlatePolygon.h"
#include "Block.h"
#include "Plane.h"
#include "Spikes.h"
#include "Enemy.h"
#include "Stairs.h"
#include "GoalModel.h"
#include "Goal.h"
#include "RouteEnemy.h"
#include "RouteFloor.h"
#include "FloorModel.h"
#include "Battery.h"
#include "Bullet.h"
#include "GoalPoint.h"
#include "VirtualFloor.h"
#include "MovingFloor.h"